version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: studentdb
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: backend-app
    restart: always
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root123
      DB_NAME: studentdb

  frontend:
    build: ./frontend
    container_name: frontend-app
    restart: always
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  mysql-data: